# Generated by Django 4.0.4 on 2022-06-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='destination_email',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='generated_url',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='origin_email',
        ),
    ]
